### ISSUE TITLE
Websockets Crashes on Boot

### ISSUE THREAD

**Issue by thebeanogamer** [ractf/core#130]
```bash
gunicorn -w 8 -b 0.0.0.0:8000 -k uvicorn.workers.UvicornWorker backend.asgi:application --config ./gunicorn_config.py
```

```py
websockets_1  | [2021-07-04 21:21:29 +0000] [41] [ERROR] Exception in ASGI application
websockets_1  | Traceback (most recent call last):
websockets_1  |   File "/usr/local/lib/python3.9/site-packages/uvicorn/protocols/websockets/websockets_impl.py", line 162, in run_asgi
websockets_1  |     result = await self.app(self.scope, self.asgi_receive, self.asgi_send)
websockets_1  |   File "/usr/local/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
websockets_1  |     return await self.app(scope, receive, send)
websockets_1  |   File "/usr/local/lib/python3.9/site-packages/channels/routing.py", line 71, in __call__
websockets_1  |     return await application(scope, receive, send)
websockets_1  |   File "/usr/local/lib/python3.9/site-packages/channels/sessions.py", line 47, in __call__
websockets_1  |     return await self.inner(dict(scope, cookies=cookies), receive, send)
websockets_1  |   File "/usr/local/lib/python3.9/site-packages/channels/sessions.py", line 254, in __call__
websockets_1  |     return await self.inner(wrapper.scope, receive, wrapper.send)
websockets_1  |   File "/usr/local/lib/python3.9/site-packages/channels/auth.py", line 181, in __call__
websockets_1  |     return await super().__call__(scope, receive, send)
websockets_1  |   File "/usr/local/lib/python3.9/site-packages/channels/middleware.py", line 26, in __call__
websockets_1  |     return await self.inner(scope, receive, send)
websockets_1  |   File "/usr/local/lib/python3.9/site-packages/channels/routing.py", line 150, in __call__
websockets_1  |     return await application(
websockets_1  |   File "/usr/local/lib/python3.9/site-packages/asgiref/compatibility.py", line 33, in new_application
websockets_1  |     instance = application(scope)
websockets_1  |   File "/usr/local/lib/python3.9/site-packages/channels/generic/websocket.py", line 159, in __init__
websockets_1  |     super().__init__(*args, **kwargs)
websockets_1  | TypeError: object.__init__() takes exactly one argument (the instance to initialize)
```

**Comment by david-cooke** [comment]
beano problem

**Comment by thebeanogamer** [comment]
Crashes under Daphne and Gunicorn

**Comment by david-cooke** [comment]
a few reverts should fix this

**Comment by thebeanogamer** [comment]
Now that probably is true, @jerbob

**Comment by 404dcd** [comment]
This looks like an issue for socketwrench
